[workspace]
members = ["drivers/*", "drivers/adbms6830b/adbms6830b_macros", "platform/*"]
resolver = "3"

[workspace.dependencies]
defmt = "1"

embedded-hal = { version = "1" }
embedded-hal-bus = { version = "0.3", features = ["async"] }
embedded-io-async = { version = "0.7", features = ["defmt"] }
embedded-hal-async = { version = "1" }
bitfield-struct = "0.13"
embassy-time = { version = "0.5.1" }

device-driver = { version = "1.0.9" }
arbitrary-int = { version = "2.1.1" }