[workspace]
members = ["drivers/*", "platform/*", "utilities/*"]
resolver = "3"

# for some reason cargo is too dumb to build a macro for host
exclude = ["utilities/cangen/cangen-macro"]

[workspace.dependencies]
defmt = "1"

embedded-hal = { version = "1" }
embedded-hal-bus = { version = "0.3", features = ["async"] }
embedded-io-async = { version = "0.7", features = ["defmt"] }
embedded-hal-async = { version = "1" }
embedded-can = "0.4.1"
bitfield-struct = "0.13"
