# this toolchain should match the stable in emabssy rs, with only the targets we need
[toolchain]
channel = "1.92"
components = [ "rust-src", "rustfmt", "llvm-tools" ]
targets = [
    "thumbv7em-none-eabi",
    "thumbv8m.main-none-eabihf",
]
