//! Helper procedural macros for the ADBMS6830B driver.

use proc_macro::TokenStream;
use proc_macro2::{Literal, TokenStream as TokenStream2};
use quote::{format_ident, quote};
use syn::parse::Parser;
use syn::punctuated::Punctuated;
use syn::{parse_macro_input, Data, DeriveInput, Expr, Fields, MetaNameValue, Token};

/// Derives an associated `const DEFAULT: Self` for an enum, set to the variant
/// marked with `#[default]`. This exists because the standard `Default` trait isn't
/// const and can't be used in a const context.
///
/// ### Example
/// ```ignore
/// #[derive(Default, BitfieldEnumDefault)]
/// enum ComparisonThresholdVoltage {
///     Mv5_1 = 0b000,
///     #[default]
///     Mv8_1 = 0b001,
///     // etc!
/// }
/// // Generates: impl ComparisonThresholdVoltage { pub const DEFAULT: Self = Self::Mv8_1; }
/// ```
#[proc_macro_derive(BitfieldEnumDefault)]
pub fn bitfield_enum_default(item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as DeriveInput);
    let name = &input.ident;

    let Data::Enum(data) = &input.data else {
        return syn::Error::new_spanned(
            &input.ident,
            "`BitfieldEnumDefault` can only be derived for enums",
        )
        .to_compile_error()
        .into();
    };

    let mut default_variants = data
        .variants
        .iter()
        .filter(|variant| variant.attrs.iter().any(|attr| attr.path().is_ident("default")));

    let Some(default_variant) = default_variants.next() else {
        return syn::Error::new_spanned(
            name,
            "`BitfieldEnumDefault` requires exactly one variant marked with `#[default]`",
        )
        .to_compile_error()
        .into();
    };

    if let Some(extra) = default_variants.next() {
        return syn::Error::new_spanned(
            &extra.ident,
            "`BitfieldEnumDefault` requires exactly one variant marked with `#[default]`",
        )
        .to_compile_error()
        .into();
    }

    let variant_ident = &default_variant.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            pub const DEFAULT: Self = Self::#variant_ident;
        }
    }
    .into()
}

/// Generates serialization code (plus some helpers) for a register group. Basically, takes a register group config struct, and creates new structs that format that register
/// group for read and write commands that can be sent directly over protocol. It handles all the PEC calculation and serialization stuff for you. Very helpful because there
/// are a lot of register groups in the ADBMS6830B and copying all these impls for each one manually would be obnoxious.
///
/// ### Using This Macro
/// Place this attribute on a register group `#[bitfield(uN)]` struct. For these purposes, a "register group struct" is a bitfield_struct 
/// whose fields are the group's configuration fields, following the register groups in the MEMORY MAP section of the
/// datasheet (starting around page 61).
/// 
/// NOTES:
/// - These bitfield_structs need to be backed by a primitive type (usually `u64`), even though most ADBMS6830B register groups are
/// only 5 or 6 bytes (rather than 8 bytes). So, you need to pass in the true size of the bitfield in bytes via the macro's `bytes` argument.
/// - This macro assumes your bitfield_struct uses LSE-first, and may break if you set a bitfield_struct to use another convention. This shouldn't be a problem
/// since bitfield_struct defaults to LSE but nonetheless.
///
/// For a given register group, this macro generates:
/// - `to_bytes`/`from_bytes` (and matching `From` impls) for the group itself, serializing the low
///   `bytes` bytes of the backing value little-endian (matching the datasheet register order),
/// - an autogenerated `### Fields` doc section appended to the struct,
/// - an `impl RegisterGroup` carrying the group's `RegisterKind`,
/// - a `<Name>WriteFrame` (only if a write command is provided), a `<Name>ReadRequest`, and a
///   `<Name>ReadResponse`, each with their PEC handling generated automatically.
///
/// ### Arguments
/// This macro requires some arguments:
/// - `bytes`: the number of wire bytes the register group occupies (e.g. `6`).
/// - `write`: `Some(<CommandFrame expr>)` if the group supports writing (e.g.
///   `Some(commands::config::wrcfga().frame())`), or `None` if it is read-only. When `None`, no
///   `<Name>WriteFrame` is generated and the group's `RegisterKind` is `ReadOnly`.
/// - `read`: the `<CommandFrame expr>` used to request a read (e.g.
///   `commands::config::rdcfga().frame()`).
///
/// ### Example
/// ```ignore
/// #[register_group(
///     bytes = 6,
///     write = Some(commands::config::wrcfga().frame()),
///     read = commands::config::rdcfga().frame(),
/// )]
/// #[bitfield(u64)]
/// pub struct ConfigA { stuff }
/// ```
#[proc_macro_attribute]
pub fn register_group(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args =
        parse_macro_input!(attr with Punctuated::<MetaNameValue, Token![,]>::parse_terminated);
    let input = parse_macro_input!(item as DeriveInput);

    match register_group_impl(&args, input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

/// Extracts the inner `CommandFrame` expression from a `write` argument that is either
/// `Some(<expr>)` or `None`.
fn extract_write_command(expr: &Expr) -> syn::Result<Option<Expr>> {
    const MESSAGE: &str = "`write` must be `Some(<CommandFrame expr>)` or `None`";
    match expr {
        Expr::Call(call) => {
            if let Expr::Path(path) = &*call.func {
                let is_some = path
                    .path
                    .segments
                    .last()
                    .is_some_and(|segment| segment.ident == "Some");
                if is_some && call.args.len() == 1 {
                    return Ok(Some(call.args[0].clone()));
                }
            }
            Err(syn::Error::new_spanned(expr, MESSAGE))
        }
        Expr::Path(path)
            if path
                .path
                .segments
                .last()
                .is_some_and(|segment| segment.ident == "None") =>
        {
            Ok(None)
        }
        _ => Err(syn::Error::new_spanned(expr, MESSAGE)),
    }
}

fn register_group_impl(
    args: &Punctuated<MetaNameValue, Token![,]>,
    mut input: DeriveInput,
) -> syn::Result<TokenStream2> {
    let name = input.ident.clone();

    // Build the auto-generated "### Fields" documentation from the struct's fields.
    let fields_doc = {
        let Data::Struct(data) = &input.data else {
            return Err(syn::Error::new_spanned(
                &name,
                "`register_group` can only be applied to structs with named fields",
            ));
        };
        let Fields::Named(fields) = &data.fields else {
            return Err(syn::Error::new_spanned(
                &name,
                "`register_group` requires named fields",
            ));
        };

        let mut doc = String::from("\n\n### Fields\n");
        for field in &fields.named {
            let ident = field.ident.as_ref().expect("named field");
            let ident_str = ident.to_string();
            // Skip reserved/padding fields; they carry no meaningful configuration.
            if ident_str.starts_with('_') {
                continue;
            }
            let (display, target) = field_type_doc(&field.ty);
            let field_doc = extract_doc(&field.attrs);
            doc.push_str(&format!(
                "- `{ident_str}`: [{display}][{target}], {field_doc}\n"
            ));
        }
        doc
    };

    // The register group must itself be a `#[bitfield(uN)]`; grab its backing type + byte width.
    let (backing_ident, backing_size) = backing_of_bitfield(&input.attrs, &name)?;

    // Parse the `bytes`, `write`, and `read` arguments.
    let mut bytes_arg: Option<usize> = None;
    let mut write_arg: Option<&Expr> = None;
    let mut read_arg: Option<&Expr> = None;
    for arg in args {
        if arg.path.is_ident("bytes") {
            let syn::Expr::Lit(syn::ExprLit { lit: syn::Lit::Int(int), .. }) = &arg.value else {
                return Err(syn::Error::new_spanned(
                    &arg.value,
                    "`bytes` must be an integer literal",
                ));
            };
            bytes_arg = Some(int.base10_parse::<usize>()?);
        } else if arg.path.is_ident("write") {
            write_arg = Some(&arg.value);
        } else if arg.path.is_ident("read") {
            read_arg = Some(&arg.value);
        } else {
            return Err(syn::Error::new_spanned(
                &arg.path,
                "unknown argument; expected `bytes`, `write`, or `read`",
            ));
        }
    }
    let Some(n) = bytes_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group` requires a `bytes = <N>` argument (the number of wire bytes)",
        ));
    };
    let Some(write_arg) = write_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group` requires a `write = Some(<CommandFrame>)` or `write = None` argument",
        ));
    };
    let Some(read_arg) = read_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group` requires a `read = <CommandFrame>` argument",
        ));
    };
    if n == 0 || n > backing_size {
        return Err(syn::Error::new_spanned(
            &name,
            format!(
                "`bytes` ({n}) must be between 1 and the bitfield's backing width ({backing_size} bytes)"
            ),
        ));
    }
    let write_command = extract_write_command(write_arg)?;

    // Append the auto-generated field documentation to the struct so `#[bitfield]` carries it over.
    // These docs get appended below whatever docs already exist on the struct
    let doc_attrs = syn::Attribute::parse_outer.parse2(quote!(#[doc = #fields_doc]))?;
    input.attrs.extend(doc_attrs);

    // Big real paths so the generated code resolves regardless of the use site's imports.
    let command_frame = quote!(crate::adbms6830b_pac::commands::CommandFrame);
    let data_pec_tx = quote!(crate::adbms6830b_pac::pec::DataPecTx);
    let data_pec_rx = quote!(crate::adbms6830b_pac::pec::DataPecRx);
    let register_kind = quote!(crate::adbms6830b_pac::registers::RegisterKind);
    let register_group_trait = quote!(crate::adbms6830b_pac::registers::RegisterGroup);

    // Byte offsets and lengths (computed via the declared `bytes` count).
    // Not using `size_of` here since that might include padding which would mess up the actual byte format
    let data_indices: Vec<Literal> = (0..n).map(Literal::usize_unsuffixed).collect();
    let command_indices: Vec<Literal> = (0..4).map(Literal::usize_unsuffixed).collect();
    let pad_zeros: Vec<Literal> = (0..(backing_size - n)).map(|_| Literal::u8_unsuffixed(0)).collect();
    let group_len = Literal::usize_unsuffixed(n);
    let write_len = Literal::usize_unsuffixed(n + 6);
    let response_len = Literal::usize_unsuffixed(n + 2);
    let pec0_index = Literal::usize_unsuffixed(n);
    let pec1_index = Literal::usize_unsuffixed(n + 1);

    let write_frame_ident = format_ident!("{}WriteFrame", name);
    let read_request_ident = format_ident!("{}ReadRequest", name);
    let read_response_ident = format_ident!("{}ReadResponse", name);

    let name_str = name.to_string();
    let write_frame_str = write_frame_ident.to_string();
    let read_request_str = read_request_ident.to_string();
    let read_response_str = read_response_ident.to_string();

    let kind_value = if write_command.is_some() {
        quote!(#register_kind::ReadWrite)
    } else {
        quote!(#register_kind::ReadOnly)
    };

    // The group serializes as the low `bytes` bytes of its bitfield backing value.
    // Using little endian here since bitfield_struct is using LSB-first, so little endian is what gets the bytes in the correct order.
    // This means that this macro would probably not work so good if used on non-LSE structs but i have a warning about it on the doc above this comment.
    // You have to explicitly set your bitfield_struct to not use LSE anyway so unlikely to happen. I mean who in their right mind would do that! 
    let group_impl = quote! {
        impl #name {
            /// Serializes the register group into its wire bytes (little-endian).
            pub const fn to_bytes(self) -> [u8; #group_len] {
                let full = self.into_bits().to_le_bytes();
                [ #( full[#data_indices] ),* ]
            }

            /// Reconstructs the register group from its wire bytes (little-endian).
            pub const fn from_bytes(bytes: [u8; #group_len]) -> Self {
                Self::from_bits(#backing_ident::from_le_bytes([
                    #( bytes[#data_indices], )*
                    #( #pad_zeros, )*
                ]))
            }
        }

        impl ::core::convert::From<#name> for [u8; #group_len] {
            fn from(value: #name) -> Self { value.to_bytes() }
        }

        impl ::core::convert::From<[u8; #group_len]> for #name {
            fn from(bytes: [u8; #group_len]) -> Self { Self::from_bytes(bytes) }
        }

        impl #register_group_trait for #name {
            const KIND: #register_kind = #kind_value;
        }
    };

    let write_frame = if let Some(write_command_expr) = &write_command {
        let struct_doc = format!(
            "A complete protocol frame for a `{name_str}` write command.\n\nThis frame contains your `{name_str}` data plus an automatically-calculated command frame header and\ndata PEC. This frame can be constructed via `{write_frame_str}::new()`, and can be serialized into bytes (for\nsending) via `to_bytes()`."
        );
        let new_doc = format!(
            "Builds a `{write_frame_str}`.\n\n### Parameters\n- `data`: The data you want to write to this register group."
        );
        quote! {
            #[doc = #struct_doc]
            #[derive(Clone, Copy, Debug)]
            pub struct #write_frame_ident {
                command: #command_frame,
                data: #name,
                data_pec: #data_pec_tx,
            }

            impl #write_frame_ident {
                #[doc = #new_doc]
                pub const fn new(data: #name) -> Self {
                    let command = #write_command_expr;
                    let data_pec = #data_pec_tx::new(&data.to_bytes());
                    Self { command, data, data_pec }
                }

                /// Serializes the frame into bytes, for sending.
                pub const fn to_bytes(self) -> [u8; #write_len] {
                    let command = self.command.to_bytes();
                    let data = self.data.to_bytes();
                    [
                        #( command[#command_indices], )*
                        #( data[#data_indices], )*
                        self.data_pec.pec0(), self.data_pec.pec1(),
                    ]
                }

                /// The command portion of this frame.
                pub const fn command(&self) -> #command_frame { self.command }

                /// The data carried by this frame.
                pub const fn data(&self) -> #name { self.data }

                /// The data PEC computed over the provided data.
                pub const fn data_pec(&self) -> #data_pec_tx { self.data_pec }
            }
        }
    } else {
        quote! {}
    };

    let read_request_doc = format!(
        "A complete protocol frame for a `{name_str}` read request.\n\nThis frame can be transmitted to request a read of this register group. The received data can be read in\nas a `{read_response_str}`.\n\nThis frame can be constructed via `{read_request_str}::new()`, and can be serialized into bytes (for\nsending) via `to_bytes()`."
    );
    let read_request_new_doc = format!("Builds a `{read_request_str}`.");
    let read_request = quote! {
        #[doc = #read_request_doc]
        #[derive(Clone, Copy, Debug)]
        pub struct #read_request_ident {
            command: #command_frame,
        }

        impl #read_request_ident {
            #[doc = #read_request_new_doc]
            pub const fn new() -> Self {
                Self { command: #read_arg }
            }

            /// Serializes the frame into bytes, for sending.
            pub const fn to_bytes(self) -> [u8; 4] {
                self.command.to_bytes()
            }

            /// The command portion of this request.
            pub const fn command(&self) -> #command_frame { self.command }
        }

        impl ::core::default::Default for #read_request_ident {
            fn default() -> Self { Self::new() }
        }
    };

    let read_response_doc = format!(
        "A complete protocol frame for a `{name_str}` read response.\n\nThis frame can be constructed from the bytes you receive after sending a `{read_request_str}`.\n\nThis frame can be constructed via `{read_response_str}::from_bytes(bytes)`, where `bytes` are the bytes received\nfrom the device following the read request."
    );
    let read_response_from_bytes_doc = format!(
        "Parses received bytes and converts them into a `{read_response_str}`.\n\n### Returns\n- `Some({read_response_str})`, if the provided `bytes` are valid. This means your read was successful, and the register\ngroup data can be read via `data()`.\n- `None`, if the PEC check fails. This typically indicates that there was some kind of error during\nreading or transmitting the response. For more info, see the `DATA PEC` section on page 53 of the datasheet."
    );
    let read_response = quote! {
        #[doc = #read_response_doc]
        #[derive(Clone, Copy, Debug)]
        pub struct #read_response_ident {
            data: #name,
            pec: #data_pec_rx,
        }

        impl #read_response_ident {
            #[doc = #read_response_from_bytes_doc]
            pub const fn from_bytes(bytes: [u8; #response_len]) -> ::core::option::Option<Self> {
                let data = [ #( bytes[#data_indices] ),* ];
                let pec = #data_pec_rx::from_bytes([bytes[#pec0_index], bytes[#pec1_index]]);
                if !pec.verify(&data) {
                    return ::core::option::Option::None;
                }
                ::core::option::Option::Some(Self {
                    data: #name::from_bytes(data),
                    pec,
                })
            }

            /// The data carried by this frame.
            pub const fn data(&self) -> #name { self.data }

            /// The device's command counter (`CCNT[5:0]`) reported alongside this response.
            pub const fn command_counter(&self) -> u8 { self.pec.ccnt() }
        }
    };

    Ok(quote! {
        #input

        #group_impl
        #write_frame
        #read_request
        #read_response
    })
}

/// Extracts the backing integer type (and its size in bytes) from a `#[bitfield(uN)]` attribute.
fn backing_of_bitfield(
    attrs: &[syn::Attribute],
    span_src: &proc_macro2::Ident,
) -> syn::Result<(proc_macro2::Ident, usize)> {
    for attr in attrs {
        if !attr.path().is_ident("bitfield") {
            continue;
        }
        if let syn::Meta::List(list) = &attr.meta {
            if let Some(proc_macro2::TokenTree::Ident(ident)) =
                list.tokens.clone().into_iter().next()
            {
                let size = match ident.to_string().as_str() {
                    "u8" => 1,
                    "u16" => 2,
                    "u32" => 4,
                    "u64" => 8,
                    "u128" => 16,
                    _ => {
                        return Err(syn::Error::new_spanned(
                            &ident,
                            "unsupported `#[bitfield]` backing type (expected u8, u16, u32, u64, or u128)",
                        ));
                    }
                };
                return Ok((ident, size));
            }
        }
    }
    Err(syn::Error::new_spanned(
        span_src,
        "`register_group` requires the struct to also carry a `#[bitfield(uN)]` attribute",
    ))
}

/// Joins a field's `///` doc comments into a single trimmed line.
fn extract_doc(attrs: &[syn::Attribute]) -> String {
    let mut parts = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        if let syn::Meta::NameValue(name_value) = &attr.meta {
            if let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(text),
                ..
            }) = &name_value.value
            {
                parts.push(text.value().trim().to_string());
            }
        }
    }
    parts.join(" ")
}

/// Returns the `(display name, intra-doc link target)` for a field type.
fn field_type_doc(ty: &syn::Type) -> (String, String) {
    const PRIMITIVES: &[&str] = &[
        "bool", "char", "f32", "f64", "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16",
        "i32", "i64", "i128", "isize",
    ];
    if let syn::Type::Path(type_path) = ty {
        let segments: Vec<String> = type_path
            .path
            .segments
            .iter()
            .map(|segment| segment.ident.to_string())
            .collect();
        if let Some(display) = segments.last().cloned() {
            if segments.len() == 1 && PRIMITIVES.contains(&display.as_str()) {
                return (display.clone(), format!("primitive@{display}"));
            }
            return (display, segments.join("::"));
        }
    }
    let rendered = quote!(#ty).to_string();
    (rendered.clone(), rendered)
}

