//! Helper procedural macros for the ADBMS6830B driver.

use proc_macro::TokenStream;
use proc_macro2::{Literal, TokenStream as TokenStream2};
use quote::quote;
use syn::parse::Parser;
use syn::punctuated::Punctuated;
use syn::{parse_macro_input, Data, DeriveInput, Expr, Fields, MetaNameValue, Token};

/// Derives an associated `const DEFAULT: Self` for an enum, set to the variant
/// marked with `#[default]`. This exists because the standard `Default` trait isn't
/// const and can't be used in a const context.
///
/// ### Example
/// ```ignore
/// #[derive(Default, BitfieldEnumDefault)]
/// enum ComparisonThresholdVoltage {
///     Mv5_1 = 0b000,
///     #[default]
///     Mv8_1 = 0b001,
///     // etc!
/// }
/// // Generates: impl ComparisonThresholdVoltage { pub const DEFAULT: Self = Self::Mv8_1; }
/// ```
#[proc_macro_derive(BitfieldEnumDefault)]
pub fn bitfield_enum_default(item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as DeriveInput);
    let name = &input.ident;

    let Data::Enum(data) = &input.data else {
        return syn::Error::new_spanned(
            &input.ident,
            "`BitfieldEnumDefault` can only be derived for enums",
        )
        .to_compile_error()
        .into();
    };

    let mut default_variants = data
        .variants
        .iter()
        .filter(|variant| variant.attrs.iter().any(|attr| attr.path().is_ident("default")));

    let Some(default_variant) = default_variants.next() else {
        return syn::Error::new_spanned(
            name,
            "`BitfieldEnumDefault` requires exactly one variant marked with `#[default]`",
        )
        .to_compile_error()
        .into();
    };

    if let Some(extra) = default_variants.next() {
        return syn::Error::new_spanned(
            &extra.ident,
            "`BitfieldEnumDefault` requires exactly one variant marked with `#[default]`",
        )
        .to_compile_error()
        .into();
    }

    let variant_ident = &default_variant.ident;
    let (impl_generics, ty_generics, where_clause) = input.generics.split_for_impl();

    quote! {
        impl #impl_generics #name #ty_generics #where_clause {
            pub const DEFAULT: Self = Self::#variant_ident;
        }
    }
    .into()
}

/// Generates wire serialization for a register group, plus its `WritableGroup` and
/// `ReadableGroup` impls.
///
/// Place this on a `#[bitfield(uN)]` struct whose fields follow a register group from the MEMORY
/// MAP section of the datasheet (starting around page 61). The backing type is usually `u64` even
/// though every ADBMS6830B register group is 6 bytes on the wire, so the real wire size is passed
/// in via `bytes`.
///
/// This macro assumes the bitfield is LSB-first, which is the `bitfield_struct` default.
///
/// For a given register group this generates:
/// - `BYTES`, `to_bytes`, `from_bytes`, and the matching `From` impls, serializing the low `bytes`
///   bytes of the backing value little-endian to match datasheet register order.
/// - An autogenerated `### Fields` doc section appended to the struct.
/// - `impl WritableGroup` if a write command was given, and `impl ReadableGroup` if a read command
///   was given. A group with neither is a compile error.
///
/// Framing (command header, per-device data PEC, device ordering) is not generated here. That stuff
/// is in the normal driver layer (SPI read() and write()).
///
/// ### Arguments
/// - `bytes`: wire bytes the group occupies. Must equal `GROUP_BYTES`.
/// - `write`: `Some(<CommandFrame expr>)` if writable, else `None`.
/// - `read`: `Some(<CommandFrame expr>)` if readable, else `None`.
///
/// ### Examples
/// A read/write group:
/// ```ignore
/// #[register_group(
///     bytes = 6,
///     write = Some(commands::config::wrcfga().frame()),
///     read = Some(commands::config::rdcfga().frame()),
/// )]
/// #[bitfield(u64)]
/// pub struct ConfigA { stuff }
/// ```
///
/// A read-only group:
/// ```ignore
/// #[register_group(
///     bytes = 6,
///     write = None,
///     read = Some(commands::cell_voltage::rdcva().frame()),
/// )]
/// #[bitfield(u64)]
/// pub struct CellVoltagesA { stuff }
/// ```
#[proc_macro_attribute]
pub fn register_group(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args =
        parse_macro_input!(attr with Punctuated::<MetaNameValue, Token![,]>::parse_terminated);
    let input = parse_macro_input!(item as DeriveInput);

    match register_group_impl(&args, input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

/// Extracts the inner `CommandFrame` expression from a `write` or `read` argument that is either
/// `Some(<expr>)` or `None`. `arg_name` (`"write"` or `"read"`) is used only for error messages.
fn extract_optional_command(expr: &Expr, arg_name: &str) -> syn::Result<Option<Expr>> {
    let message = || format!("`{arg_name}` must be `Some(<CommandFrame expr>)` or `None`");
    match expr {
        Expr::Call(call) => {
            if let Expr::Path(path) = &*call.func {
                let is_some = path
                    .path
                    .segments
                    .last()
                    .is_some_and(|segment| segment.ident == "Some");
                if is_some && call.args.len() == 1 {
                    return Ok(Some(call.args[0].clone()));
                }
            }
            Err(syn::Error::new_spanned(expr, message()))
        }
        Expr::Path(path)
            if path
                .path
                .segments
                .last()
                .is_some_and(|segment| segment.ident == "None") =>
        {
            Ok(None)
        }
        _ => Err(syn::Error::new_spanned(expr, message())),
    }
}

fn register_group_impl(
    args: &Punctuated<MetaNameValue, Token![,]>,
    mut input: DeriveInput,
) -> syn::Result<TokenStream2> {
    let name = input.ident.clone();

    // Build the auto-generated "### Fields" documentation from the struct's fields.
    let fields_doc = {
        let Data::Struct(data) = &input.data else {
            return Err(syn::Error::new_spanned(
                &name,
                "`register_group` can only be applied to structs with named fields",
            ));
        };
        let Fields::Named(fields) = &data.fields else {
            return Err(syn::Error::new_spanned(
                &name,
                "`register_group` requires named fields",
            ));
        };

        let mut doc = String::from("\n\n### Fields\n");
        for field in &fields.named {
            let ident = field.ident.as_ref().expect("named field");
            let ident_str = ident.to_string();
            // Skip reserved/padding fields; they carry no meaningful configuration.
            if ident_str.starts_with('_') {
                continue;
            }
            let (display, target) = field_type_doc(&field.ty);
            let field_doc = extract_doc(&field.attrs);
            doc.push_str(&format!(
                "- `{ident_str}`: [{display}][{target}], {field_doc}\n"
            ));
        }
        doc
    };

    // The register group needs to be a `#[bitfield(uN)]`, so we can grab the backing type etc
    let (backing_ident, backing_size) = backing_of_bitfield(&input.attrs, &name)?;

    // Parse the `bytes`, `write`, and `read` arguments.
    let mut bytes_arg: Option<usize> = None;
    let mut write_arg: Option<&Expr> = None;
    let mut read_arg: Option<&Expr> = None;
    for arg in args {
        if arg.path.is_ident("bytes") {
            let syn::Expr::Lit(syn::ExprLit { lit: syn::Lit::Int(int), .. }) = &arg.value else {
                return Err(syn::Error::new_spanned(
                    &arg.value,
                    "`bytes` must be an integer literal",
                ));
            };
            bytes_arg = Some(int.base10_parse::<usize>()?);
        } else if arg.path.is_ident("write") {
            write_arg = Some(&arg.value);
        } else if arg.path.is_ident("read") {
            read_arg = Some(&arg.value);
        } else {
            return Err(syn::Error::new_spanned(
                &arg.path,
                "unknown argument; expected `bytes`, `write`, or `read`",
            ));
        }
    }
    let Some(n) = bytes_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group` requires a `bytes = <N>` argument (the number of wire bytes)",
        ));
    };
    let Some(write_arg) = write_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group` requires a `write = Some(<CommandFrame>)` or `write = None` argument",
        ));
    };
    let Some(read_arg) = read_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group` requires a `read = Some(<CommandFrame>)` or `read = None` argument",
        ));
    };
    if n == 0 || n > backing_size {
        return Err(syn::Error::new_spanned(
            &name,
            format!(
                "`bytes` ({n}) must be between 1 and the bitfield's backing width ({backing_size} bytes)"
            ),
        ));
    }
    let write_command = extract_optional_command(write_arg, "write")?;
    let read_command = extract_optional_command(read_arg, "read")?;
    if write_command.is_none() && read_command.is_none() {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group` needs at least one of `write` or `read` to be `Some(...)`; a group that is neither readable nor writable is not valid",
        ));
    }

    // Append the auto-generated field documentation to the struct so `#[bitfield]` carries it over.
    // These docs get appended below whatever docs already exist on the struct
    let doc_attrs = syn::Attribute::parse_outer.parse2(quote!(#[doc = #fields_doc]))?;
    input.attrs.extend(doc_attrs);

    // Big real paths so the generated code resolves regardless of the use site's imports.
    let command_frame = quote!(crate::chip::commands::CommandFrame);
    let writable = quote!(crate::chip::registers::WritableGroup);
    let readable = quote!(crate::chip::registers::ReadableGroup);
    let group_bytes = quote!(crate::chip::registers::GROUP_BYTES);

    // Byte offsets and lengths (computed via the declared `bytes` count).
    // Not using `size_of` here since that might include padding which would mess up the actual byte format
    let data_indices: Vec<Literal> = (0..n).map(Literal::usize_unsuffixed).collect();
    let pad_zeros: Vec<Literal> = (0..(backing_size - n)).map(|_| Literal::u8_unsuffixed(0)).collect();
    let group_len = Literal::usize_unsuffixed(n);

    // The group serializes as the low `bytes` bytes of its bitfield backing value.
    // Little endian, since bitfield_struct is LSB-first and that puts the bytes in datasheet register order.
    let group_impl = quote! {
        impl #name {
            /// The number of wire bytes this register group occupies.
            pub const BYTES: usize = #group_len;

            /// Serializes the register group into its wire bytes (little-endian).
            pub const fn to_bytes(self) -> [u8; #group_len] {
                let full = self.into_bits().to_le_bytes();
                [ #( full[#data_indices] ),* ]
            }

            /// Reconstructs the register group from its wire bytes (little-endian).
            pub const fn from_bytes(bytes: [u8; #group_len]) -> Self {
                Self::from_bits(#backing_ident::from_le_bytes([
                    #( bytes[#data_indices], )*
                    #( #pad_zeros, )*
                ]))
            }
        }

        impl ::core::convert::From<#name> for [u8; #group_len] {
            fn from(value: #name) -> Self { value.to_bytes() }
        }

        impl ::core::convert::From<[u8; #group_len]> for #name {
            fn from(bytes: [u8; #group_len]) -> Self { Self::from_bytes(bytes) }
        }
    };

    let writable_impl = match &write_command {
        Some(cmd) => quote! {
            impl #writable for #name {
                const WRITE_COMMAND: #command_frame = #cmd;
                fn to_bytes(self) -> [u8; #group_bytes] { self.to_bytes() }
            }
        },
        None => quote! {},
    };

    let readable_impl = match &read_command {
        Some(cmd) => quote! {
            impl #readable for #name {
                const READ_COMMAND: #command_frame = #cmd;
                fn from_bytes(bytes: [u8; #group_bytes]) -> Self { Self::from_bytes(bytes) }
            }
        },
        None => quote! {},
    };

    Ok(quote! {
        #input

        #group_impl
        #writable_impl
        #readable_impl
    })
}

/// Extracts the backing integer type (and its size in bytes) from a `#[bitfield(uN)]` attribute.
fn backing_of_bitfield(
    attrs: &[syn::Attribute],
    span_src: &proc_macro2::Ident,
) -> syn::Result<(proc_macro2::Ident, usize)> {
    for attr in attrs {
        if !attr.path().is_ident("bitfield") {
            continue;
        }
        if let syn::Meta::List(list) = &attr.meta {
            if let Some(proc_macro2::TokenTree::Ident(ident)) =
                list.tokens.clone().into_iter().next()
            {
                let size = match ident.to_string().as_str() {
                    "u8" => 1,
                    "u16" => 2,
                    "u32" => 4,
                    "u64" => 8,
                    "u128" => 16,
                    _ => {
                        return Err(syn::Error::new_spanned(
                            &ident,
                            "unsupported `#[bitfield]` backing type (expected u8, u16, u32, u64, or u128)",
                        ));
                    }
                };
                return Ok((ident, size));
            }
        }
    }
    Err(syn::Error::new_spanned(
        span_src,
        "`register_group` requires the struct to also carry a `#[bitfield(uN)]` attribute",
    ))
}

/// Joins a field's `///` doc comments into a single trimmed line.
fn extract_doc(attrs: &[syn::Attribute]) -> String {
    let mut parts = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        if let syn::Meta::NameValue(name_value) = &attr.meta {
            if let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(text),
                ..
            }) = &name_value.value
            {
                parts.push(text.value().trim().to_string());
            }
        }
    }
    parts.join(" ")
}

/// Returns the `(display name, intra-doc link target)` for a field type.
fn field_type_doc(ty: &syn::Type) -> (String, String) {
    const PRIMITIVES: &[&str] = &[
        "bool", "char", "f32", "f64", "u8", "u16", "u32", "u64", "u128", "usize", "i8", "i16",
        "i32", "i64", "i128", "isize",
    ];
    if let syn::Type::Path(type_path) = ty {
        let segments: Vec<String> = type_path
            .path
            .segments
            .iter()
            .map(|segment| segment.ident.to_string())
            .collect();
        if let Some(display) = segments.last().cloned() {
            if segments.len() == 1 && PRIMITIVES.contains(&display.as_str()) {
                return (display.clone(), format!("primitive@{display}"));
            }
            return (display, segments.join("::"));
        }
    }
    let rendered = quote!(#ty).to_string();
    (rendered.clone(), rendered)
}

/// Attribute macro for an "aggregate" read-only register group (a struct that just contains a
/// bunch of other register groups generated by `#[register_group]`). This is useful for read-all commands
/// where we can read multiple register groups in one go.
///
/// Each member type must expose `const BYTES: usize`, `const fn to_bytes(self) -> [u8; BYTES]`, and
/// `const fn from_bytes([u8; BYTES]) -> Self`. Register groups generated by `register_group` already
/// provide these.
///
/// For a given aggregate, this macro generates:
/// - `BYTES`, `to_bytes`, and `from_bytes` for the aggregate itself,
/// - an `impl RegisterGroup` carrying the group's `RegisterKind` (derived from which commands are
///   present, same as `register_group`),
/// - a `<Name>WriteFrame` (only if a write command is provided), and a `<Name>ReadRequest` +
///   `<Name>ReadResponse` (only if a read command is provided), each with a single PEC over the
///   whole packet.
///
/// ### Single-IC Only (No Daisy Chains)
/// Unlike `register_group`, this macro deliberately generates no `daisychain_*` helpers, because
/// the read-all commands cannot be used on a daisy chain at all. See the READ ALL COMMANDS section on page 41 of the datasheet.
///
/// So, in a daisy chain, use SNAP/UNSNAP around ordinary per-group reads instead. The snapshot commands
/// are explicitly "supported in all applications" and give you the same coherency guarantee, and the
/// individual `register_group` types do provide `daisychain_*` helpers.
///
/// ### Arguments
/// - `read`: `Some(<CommandFrame expr>)` used to request the read (e.g.
///   `Some(commands::cell_voltage::rdcvall().frame())`), or `None` if the aggregate is write-only.
/// - `write`: `Some(<CommandFrame expr>)` if the aggregate supports a bulk write, or `None`. When
///   `None`, no `<Name>WriteFrame` is generated.
///
/// Same rules as `register_group`: `write` and `read` both take `Some(...)`/`None`, and at least one
/// must be `Some`.
///
/// ### Examples
/// A read-only "read all" aggregate:
/// ```ignore
/// #[register_group_aggregate(
///     write = None,
///     read = Some(commands::cell_voltage::rdcvall().frame()),
/// )]
/// #[derive(Clone, Copy, Debug)]
/// pub struct CellVoltagesAll {
///     pub a: CellVoltagesA,
///     // ...
///     pub c16v: types::CellVoltage,
/// }
/// ```
///
/// A write-only bulk aggregate:
/// ```ignore
/// #[register_group_aggregate(
///     write = Some(commands::config::wrcfgall().frame()),
///     read = None,
/// )]
/// #[derive(Clone, Copy, Debug)]
/// pub struct ConfigAll {
///     pub a: ConfigA,
///     pub b: ConfigB,
/// }
/// ```
#[proc_macro_attribute]
pub fn register_group_aggregate(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args =
        parse_macro_input!(attr with Punctuated::<MetaNameValue, Token![,]>::parse_terminated);
    let input = parse_macro_input!(item as DeriveInput);

    match register_group_aggregate_impl(&args, input) {
        Ok(tokens) => tokens.into(),
        Err(err) => err.to_compile_error().into(),
    }
}

fn register_group_aggregate_impl(
    args: &Punctuated<MetaNameValue, Token![,]>,
    input: DeriveInput,
) -> syn::Result<TokenStream2> {
    let name = input.ident.clone();

    // Collect the aggregate's member fields.
    let (field_idents, field_types) = {
        let Data::Struct(data) = &input.data else {
            return Err(syn::Error::new_spanned(
                &name,
                "`register_group_aggregate` can only be applied to structs with named fields",
            ));
        };
        let Fields::Named(fields) = &data.fields else {
            return Err(syn::Error::new_spanned(
                &name,
                "`register_group_aggregate` requires named fields",
            ));
        };
        if fields.named.is_empty() {
            return Err(syn::Error::new_spanned(
                &name,
                "`register_group_aggregate` requires at least one member field",
            ));
        }
        let idents: Vec<proc_macro2::Ident> = fields
            .named
            .iter()
            .map(|field| field.ident.clone().expect("named field"))
            .collect();
        let types: Vec<syn::Type> = fields.named.iter().map(|field| field.ty.clone()).collect();
        (idents, types)
    };

    // Parse the `read` and `write` arguments (both required, each `Some(...)` or `None`).
    let mut read_arg: Option<&Expr> = None;
    let mut write_arg: Option<&Expr> = None;
    for arg in args {
        if arg.path.is_ident("read") {
            read_arg = Some(&arg.value);
        } else if arg.path.is_ident("write") {
            write_arg = Some(&arg.value);
        } else {
            return Err(syn::Error::new_spanned(
                &arg.path,
                "unknown argument; expected `read` or `write`",
            ));
        }
    }
    let Some(write_arg) = write_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group_aggregate` requires a `write = Some(<CommandFrame>)` or `write = None` argument",
        ));
    };
    let Some(read_arg) = read_arg else {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group_aggregate` requires a `read = Some(<CommandFrame>)` or `read = None` argument",
        ));
    };
    let write_command = extract_optional_command(write_arg, "write")?;
    let read_command = extract_optional_command(read_arg, "read")?;
    if write_command.is_none() && read_command.is_none() {
        return Err(syn::Error::new_spanned(
            &name,
            "`register_group_aggregate` needs at least one of `write` or `read` to be `Some(...)`; an aggregate that is neither readable nor writable is not valid",
        ));
    }

    let group_impl = quote! {
        impl #name {
            /// The total number of wire bytes this aggregate occupies (the sum of its members).
            pub const BYTES: usize = 0 #( + <#field_types>::BYTES )*;

            /// Serializes the aggregate into its wire bytes, concatenating each member in field order.
            pub const fn to_bytes(self) -> [u8; Self::BYTES] {
                let mut out = [0u8; Self::BYTES];
                let mut offset = 0usize;
                #(
                    {
                        let part = self.#field_idents.to_bytes();
                        let mut i = 0usize;
                        while i < part.len() {
                            out[offset + i] = part[i];
                            i += 1;
                        }
                        offset += part.len();
                    }
                )*
                let _ = offset;
                out
            }

            /// Reconstructs the aggregate from its wire bytes, splitting each member in field order.
            pub const fn from_bytes(bytes: [u8; Self::BYTES]) -> Self {
                let mut offset = 0usize;
                #(
                    let #field_idents = {
                        let mut buf = [0u8; <#field_types>::BYTES];
                        let mut i = 0usize;
                        while i < buf.len() {
                            buf[i] = bytes[offset + i];
                            i += 1;
                        }
                        offset += buf.len();
                        <#field_types>::from_bytes(buf)
                    };
                )*
                let _ = offset;
                Self { #( #field_idents ),* }
            }
        }
    };

    Ok(quote! {
        #input

        #group_impl
    })
}

